steps:
- name: gcr.io/cloud-builders/docker
  id: Build
  dir: bank-api-gke
  args:
  - build
  - -t
  - us-central1-docker.pkg.dev/gcp-class-14/parths-bank-images/bank-api:latest
  - .

- name: gcr.io/cloud-builders/docker
  id: Push
  args:
  - push
  - us-central1-docker.pkg.dev/gcp-class-14/parths-bank-images/bank-api:latest

- name: gcr.io/cloud-builders/gke-deploy
  id: Deploy
  args:
  - run
  - --filename=bank-api-gke/backend.yaml
  - --location=us-central1
  - --cluster=parths-bankproject-cluster


options:
  logging: CLOUD_LOGGING_ONLY
