steps:
- name: gcr.io/cloud-builders/docker
  id: Build
  dir: bank-web-gke
  args:
  - build
  - -f
  - Dockerfile-before-https-first
  - -t
  - us-central1-docker.pkg.dev/gcp-class-14/parths-bank-images/bank-web:$SHORT_SHA
  - .

- name: gcr.io/cloud-builders/docker
  id: Push
  args:
  - push
  - us-central1-docker.pkg.dev/gcp-class-14/parths-bank-images/bank-web:$SHORT_SHA

- name: gcr.io/cloud-builders/gke-deploy
  id: Deploy
  args:
  - run
  - --filename=bank-web-gke/frontend.yaml
  - --location=us-central1
  - --cluster=parths-bankproject-cluster

images:
- us-central1-docker.pkg.dev/gcp-class-14/parths-bank-images/bank-web:$SHORT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
