steps:
- name: gcr.io/cloud-builders/docker
  id: Build
  dir: bank-web-gke
  args:
  - build
  - --no-cache
  - -f
  - Dockerfile-before-https-first
  - -t
  - us-central1-docker.pkg.dev/gcp-class-14/parths-bank-images/bank-web:latest
  - --build-arg
  - REACT_APP_API_URL=http://35.239.119.95
  - .

- name: gcr.io/cloud-builders/docker
  id: Push
  args:
  - push
  - us-central1-docker.pkg.dev/gcp-class-14/parths-bank-images/bank-web:latest

- name: gcr.io/cloud-builders/gke-deploy
  id: Deploy
  args:
  - run
  - --filename=bank-web-gke/frontend.yaml
  - --location=us-central1
  - --cluster=parths-bankproject-cluster

options:
  logging: CLOUD_LOGGING_ONLY
