steps:
- name: gcr.io/cloud-builders/docker
  id: Build
  args:
  - build
  - -f
  - FRONTEND_DOCKERFILE_NAME
  - -t
  - us-central1-docker.pkg.dev/gcp-class-14/parths-bank-images/bank-web:$SHORT_SHA
  - .
  dir: bank-web-gke

- name: gcr.io/cloud-builders/docker
  id: Push
  args:
  - push
  - us-central1-docker.pkg.dev/gcp-class-14/parths-bank-images/bank-web:$SHORT_SHA

images:
- us-central1-docker.pkg.dev/gcp-class-14/parths-bank-images/bank-web:$SHORT_SHA
